#pragma once
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#define NOKERNEL
#define NOSERVICE
#define NOSOUND
#define NOCOMM
#define NODRIVERS
#define NOLOGERROR
#define NOPROFILER
#define NOMEMMGR
#define NOLFILEIO
#define NOATOM
#define NOLANGUAGE
#define NOLSTRING
#define NODBCS
#define NOSCALABLEFONT
#define NOSYSMETRICS
#define NOSYSTEMPARAMSINFO
#define NOMCX
#define NOIME
#include <Windows.h>
